version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet9_dev_container
    ports:
      - "5000:80"
    volumes:
      - ./src:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=TestString

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
